name: Android Build

on:
  push:
    branches:
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties
          echo "storeFile=keystore.jks" >> key.properties

      - name: Download Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > keystore.jks

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: droidcicd-1.0.0.apk
          path: app/build/outputs/apk/release/app-release.apk